### ISSUE TITLE
OSError: cannot open resource

### ISSUE THREAD

**Issue by abright01** [X-rayLaser/Keras-HTR#1]
Having trouble creating a synthetic dataset. Created a virtual environment in Pycharm IDE, imported requirements, and tried to build dataset. Any ideas?

``` 
(venv) Keras-HTR User$ python build_lines_dataset.py --source='keras_htr.data_source.synthetic.SyntheticSource' --destination=htr_temp
keras_htr.data_source.synthetic.SyntheticSource
keras_htr.preprocessing.Cnn1drnnCtcPreprocessor
All existing data in the directory htr_temp will be erased. Continue (Y/N) ?Y
Traceback (most recent call last):
  File "build_lines_dataset.py", line 98, in <module>
    create_lines_dataset(source, preprocessor, destination_folder=destination,
  File "/Keras-HTR/keras_htr/dataset_building.py", line 14, in create_lines_dataset
    extract_lines(data_source, temp_folder, size, train_fraction, val_fraction)
  File "/Keras-HTR/keras_htr/dataset_building.py", line 62, in extract_lines
    for triple in split_examples(example_generator, size, train_fraction, val_fraction):
  File "Keras-HTR/keras_htr/dataset_building.py", line 135, in split_examples
    for count, example in enumerate(example_generator):
  File "/Keras-HTR/keras_htr/data_source/synthetic.py", line 14, in __iter__
    image = self.create_image(w)
  File "/Keras-HTR/keras_htr/data_source/synthetic.py", line 20, in create_image
    fnt = ImageFont.truetype('Pillow/Tests/fonts/FreeMono.ttf', 40)
  File "/venv/lib/python3.8/site-packages/PIL/ImageFont.py", line 655, in truetype
    return freetype(font)
  File "/venv/lib/python3.8/site-packages/PIL/ImageFont.py", line 652, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/venv/lib/python3.8/site-packages/PIL/ImageFont.py", line 193, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

**Comment by abright01** [comment]
Solution -- MacOS need to download font "FreeMono.ttf" from 
https://github.com/python-pillow/Pillow/blob/master/Tests/fonts/FreeMono.ttf 
and change the path 'Pillow/Tests/fonts/FreeMono.ttf' to wherever you save the font.

**Comment by X-rayLaser** [comment]
Appollogies. I wasn't checking github in awhile.
Thanks for creating an issue and providing the solution!
